[alias]
bb = "build --all --all-features --release"
be = "build --examples --target wasm32-unknown-unknown --release"
tt = "nextest run --release --all --no-fail-fast"
cc = "clippy --all -- -D warnings"