name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: rustfmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy --all -- -D warnings

      - name: build
        run: cargo build --all --all-features --release

      - name: tests
        uses: taiki-e/install-action@nextest
      - name: nextest run
        run: cargo nextest run --release --all --no-fail-fast --features unified-opcodes
